# -*- coding: utf-8 -*-
"""Copy of Adult-MLP/CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RdOtrMQt-6n3Hb_Eyw7XUN3Ev4EafPLA
"""

!pip install ucimlrepo

from ucimlrepo import fetch_ucirepo

# fetch dataset
adult = fetch_ucirepo(id=2)

# data (as pandas dataframes)
X = adult.data.features
y = adult.data.targets

y['income'] = y['income'].apply(lambda x: 1 if '>50K' in x else 0)
print (y)

import numpy as np

X.replace('?', np.nan, inplace=True)
X.dropna(inplace=True)  # or use imputation if preferred

import numpy as np

X.replace('?', np.nan, inplace=True)
X.dropna(inplace=True)
y = y.loc[X.index]  # sync labels with filtered rows

import pandas as pd
from sklearn.preprocessing import StandardScaler
X_full = X.copy()

# Identify column types
categorical_cols = X.select_dtypes(include='object').columns.tolist()
numerical_cols = X.select_dtypes(include=['int64', 'float64']).columns.tolist()

# One-hot encode categoricals
X_encoded = pd.get_dummies(X[categorical_cols])

# Scale numericals
scaler = StandardScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X[numerical_cols]), columns=numerical_cols, index=X.index)

# Combine all features
X_preprocessed = pd.concat([X_scaled, X_encoded], axis=1)

print (X_preprocessed)

from sklearn.model_selection import train_test_split

X_train, X_temp, y_train, y_temp = train_test_split(
    X_preprocessed.values, y.values.ravel(), test_size=0.3, stratify=y, random_state=42)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, stratify=y_temp, random_state=42)

import torch
import numpy as np # Import numpy
from torch.utils.data import TensorDataset, DataLoader

def to_tensor_loader(X, y, batch_size=64, shuffle=False):
    # Ensure X is of a numerical type suitable for torch.tensor
    X = X.astype(np.float32) # Explicitly convert to float32
    X_t = torch.tensor(X, dtype=torch.float32)
    y_t = torch.tensor(y, dtype=torch.long)
    return DataLoader(TensorDataset(X_t, y_t), batch_size=batch_size, shuffle=shuffle)

train_loader = to_tensor_loader(X_train, y_train, shuffle=True)
val_loader = to_tensor_loader(X_val, y_val)
test_loader = to_tensor_loader(X_test, y_test)

import torch.nn as nn

class MLP(nn.Module):
    def __init__(self, input_dim, hidden_dims=[128, 64], output_dim=2):
        super(MLP, self).__init__()
        layers = []

        dims = [input_dim] + hidden_dims
        for i in range(len(dims) - 1):
            layers.append(nn.Linear(dims[i], dims[i + 1]))
            layers.append(nn.ReLU())
            layers.append(nn.Dropout(0.3))  # optional: helps prevent overfitting

        layers.append(nn.Linear(dims[-1], output_dim))
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x)

import torch.nn.functional as F
from sklearn.metrics import accuracy_score, f1_score

def train(model, loader, optimizer, criterion, device):
    model.train()
    total_loss = 0
    for X, y in loader:
        X, y = X.to(device), y.to(device)

        optimizer.zero_grad()
        logits = model(X)
        loss = criterion(logits, y)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
    return total_loss / len(loader)

def evaluate(model, loader, device):
    model.eval()
    all_preds = []
    all_labels = []
    with torch.no_grad():
        for X, y in loader:
            X, y = X.to(device), y.to(device)
            logits = model(X)
            preds = torch.argmax(logits, dim=1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(y.cpu().numpy())
    acc = accuracy_score(all_labels, all_preds)
    f1 = f1_score(all_labels, all_preds)
    return acc, f1

import torch

# Set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Initialize model
input_dim = X_train.shape[1]
model = MLP(input_dim=input_dim).to(device)

# Optimizer and loss
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
criterion = nn.CrossEntropyLoss()

# Training loop
num_epochs = 20
for epoch in range(num_epochs):
    train_loss = train(model, train_loader, optimizer, criterion, device)
    val_acc, val_f1 = evaluate(model, val_loader, device)
    print(f"Epoch {epoch+1}/{num_epochs} | Train Loss: {train_loss:.4f} | Val Acc: {val_acc:.4f} | Val F1: {val_f1:.4f}")

"""## CNN on Adult Dataset

"""

import torch.nn as nn

class TabularCNN(nn.Module):
    def __init__(self, input_side, num_classes=2):
        super(TabularCNN, self).__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(1, 16, kernel_size=3, padding=1), nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Conv2d(16, 32, kernel_size=3, padding=1), nn.ReLU(),
            nn.MaxPool2d(2)
        )
        conv_output_size = (input_side // 4) ** 2 * 32  # 2 poolings
        self.fc = nn.Sequential(
            nn.Linear(conv_output_size, 64), nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(64, num_classes)
        )

    def forward(self, x):
        x = self.conv(x)
        x = x.view(x.size(0), -1)  # flatten
        return self.fc(x)

def train_cnn(model, loader, optimizer, criterion, device, side, pad_size):
    model.train()
    total_loss = 0
    for X, y in loader:
        X, y = X.to(device), y.to(device)
        X = torch.nn.functional.pad(X, (0, pad_size))  # Pad
        X = X.view(-1, 1, side, side)

        optimizer.zero_grad()
        outputs = model(X)
        loss = criterion(outputs, y)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    return total_loss / len(loader)

def evaluate_cnn(model, loader, device, side, pad_size):
    model.eval()
    y_true, y_pred = [], []
    with torch.no_grad():
        for X, y in loader:
            X, y = X.to(device), y.to(device)
            X = torch.nn.functional.pad(X, (0, pad_size))
            X = X.view(-1, 1, side, side)

            outputs = model(X)
            preds = outputs.argmax(dim=1)
            y_true.extend(y.cpu().numpy())
            y_pred.extend(preds.cpu().numpy())
    from sklearn.metrics import accuracy_score, f1_score
    return accuracy_score(y_true, y_pred), f1_score(y_true, y_pred)

print(X_train.shape)

from ucimlrepo import fetch_ucirepo
import pandas as pd
import numpy as np

adult = fetch_ucirepo(id=2)
X = adult.data.features
y = adult.data.targets
y['income'] = y['income'].apply(lambda x: 1 if '>50K' in x else 0)

!pip install ucimlrepo

from ucimlrepo import fetch_ucirepo
import pandas as pd
import numpy as np

adult = fetch_ucirepo(id=2)
X = adult.data.features
y = adult.data.targets
y['income'] = y['income'].apply(lambda x: 1 if '>50K' in x else 0)

from sklearn.preprocessing import StandardScaler

# Clean missing values
X.replace('?', np.nan, inplace=True)
X.dropna(inplace=True)
y = y.loc[X.index]

# Encode and scale
categorical_cols = X.select_dtypes(include='object').columns.tolist()
numerical_cols = X.select_dtypes(include=['int64', 'float64']).columns.tolist()

X_encoded = pd.get_dummies(X[categorical_cols])
X_scaled = pd.DataFrame(StandardScaler().fit_transform(X[numerical_cols]), columns=numerical_cols, index=X.index)
X_preprocessed = pd.concat([X_scaled, X_encoded], axis=1)

from sklearn.model_selection import train_test_split

X_train, X_temp, y_train, y_temp = train_test_split(
    X_preprocessed.values, y.values.ravel(), test_size=0.3, stratify=y, random_state=42)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, stratify=y_temp, random_state=42)

import torch
import numpy as np # Import numpy
from torch.utils.data import TensorDataset, DataLoader

def to_tensor_loader(X, y, batch_size=64, shuffle=False):
    # Ensure X is of a numerical type suitable for torch.tensor
    X = X.astype(np.float32) # Explicitly convert to float32
    X_t = torch.tensor(X, dtype=torch.float32)
    y_t = torch.tensor(y, dtype=torch.long)
    return DataLoader(TensorDataset(X_t, y_t), batch_size=batch_size, shuffle=shuffle)

train_loader = to_tensor_loader(X_train, y_train, shuffle=True)
val_loader   = to_tensor_loader(X_val, y_val)
test_loader  = to_tensor_loader(X_test, y_test)

print(X_train.shape)

import math

side = math.ceil(X_train.shape[1] ** 0.5)
pad_size = side**2 - X_train.shape[1]
print(f"Input reshaped to: {side}x{side} with {pad_size} zero-padding")

import torch.nn as nn

class TabularCNN(nn.Module):
    def __init__(self, input_side, num_classes=2):
        super(TabularCNN, self).__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(1, 16, kernel_size=3, padding=1), nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Conv2d(16, 32, kernel_size=3, padding=1), nn.ReLU(),
            nn.MaxPool2d(2)
        )
        conv_output_size = (input_side // 4) ** 2 * 32
        self.fc = nn.Sequential(
            nn.Linear(conv_output_size, 64), nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(64, num_classes)
        )

    def forward(self, x):
        x = self.conv(x)
        x = x.view(x.size(0), -1)
        return self.fc(x)

from sklearn.metrics import accuracy_score, f1_score

def train_cnn(model, loader, optimizer, criterion, device, side, pad_size):
    model.train()
    total_loss = 0
    for X, y in loader:
        X, y = X.to(device), y.to(device)
        X = torch.nn.functional.pad(X, (0, pad_size))
        X = X.view(-1, 1, side, side)
        optimizer.zero_grad()
        out = model(X)
        loss = criterion(out, y)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    return total_loss / len(loader)

def evaluate_cnn(model, loader, device, side, pad_size):
    model.eval()
    y_true, y_pred = [], []
    with torch.no_grad():
        for X, y in loader:
            X, y = X.to(device), y.to(device)
            X = torch.nn.functional.pad(X, (0, pad_size))
            X = X.view(-1, 1, side, side)
            out = model(X)
            pred = out.argmax(dim=1)
            y_true.extend(y.cpu().numpy())
            y_pred.extend(pred.cpu().numpy())
    return accuracy_score(y_true, y_pred), f1_score(y_true, y_pred)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = TabularCNN(input_side=side).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
criterion = nn.CrossEntropyLoss()

for epoch in range(20):
    loss = train_cnn(model, train_loader, optimizer, criterion, device, side, pad_size)
    acc, f1 = evaluate_cnn(model, val_loader, device, side, pad_size)
    print(f"Epoch {epoch+1} | Train Loss: {loss:.4f} | Val Acc: {acc:.4f} | Val F1: {f1:.4f}")